// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskControl.Models;

public partial class Person
{
    public int PersonId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int Age { get; set; }

    public string PhoneNumber { get; set; }

    public virtual ICollection<TaskPerson> TaskPeople { get; set; } = new List<TaskPerson>();
}