// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskControl.Models;

public partial class Status
{
    public int StatusId { get; set; }

    public string Status1 { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}