// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskControl.Models;

public partial class TaskPerson
{
    public int TaskId { get; set; }

    public int PersonId { get; set; }

    public DateOnly TimeAssigned { get; set; }

    public virtual Person Person { get; set; }

    public virtual Task Task { get; set; }
}