// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskControl.Models;

public partial class Task
{
    public int TaskId { get; set; }

    public string Task1 { get; set; }

    public int StatusId { get; set; }

    public int PriorityId { get; set; }

    public DateOnly DueDate { get; set; }

    public DateOnly CreatedAt { get; set; }

    public virtual Priority Priority { get; set; }

    public virtual Status Status { get; set; }

    public virtual ICollection<TaskCategory> TaskCategories { get; set; } = new List<TaskCategory>();

    public virtual ICollection<TaskPerson> TaskPeople { get; set; } = new List<TaskPerson>();
}